# Generated by Django 3.0.5 on 2020-04-15 14:27

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='parent_cell_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='US'),
        ),
    ]
