# Generated by Django 3.0.5 on 2020-04-15 14:06

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('D_O_B', models.DateField()),
                ('parent_first_name', models.CharField(max_length=20)),
                ('parent_last_name', models.CharField(max_length=20)),
                ('parent_cell_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('school', models.CharField(choices=[('GWHS', 'Gateway High School'), ('SCHS', 'St. Cloud High School'), ('CHS', 'Celebration High School'), ('OHS', 'Osceola High School'), ('PATHS', 'PATHS'), ('HHS', 'Harmony High School'), ('PHS', 'Poinciana High School'), ('NCHS', 'Neocity Academy'), ('LHS', 'Libery High School'), ('NDHS', 'New Dimensions High School'), ('NEW-BEG', 'New Beginnings')], max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(default='Florida', max_length=7)),
                ('zipcode', models.PositiveIntegerField()),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
