# Generated by Django 3.0.5 on 2020-04-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='zipcode',
            field=models.CharField(max_length=5),
        ),
    ]
