# Generated by Django 3.0.5 on 2020-04-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='hours_completed',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
